apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_USER: bmVvbmRiX29uZXI=
  DB_PASSWORD: bnBnX0xqNUQ3RnF0VmVISQ==
  SECRET_KEY: ZGFuZ2Vyb2luY3JlYWRpYmxlLWNsYXZlX2ZlcnJldGVyaWFfdGVzdGluZ18yMDI2